version: '3.4'

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    container_name: project_redis

  db:
    image: mariadb:latest
    ports: 
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=DM
    container_name: project_db

  backend:
    image: developers_mate_backend
    build:
      context: ./backend
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    container_name: project_backend
    depends_on:
      - redis
      - db
  
  frontend:
    image: developers_mate_frontend
    build:
      context: ./developers-mate
    ports:
      - 3000:3000
    environment:
      - REACT_APP_SERVER_URL=backend:8000
      - REACT_APP_WEBSOCKET_URL=backend:8000
    volumes:
      - react_build:/react/build
    container_name: project_frontend
  
  nginx:
    image: nginx:latest
    ports: 
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
    depends_on:
      - frontend
volumes:
  react_build:  
